site_name: segpy
site_url: https://neurobioinfo.github.io/
nav:
    - Home: index.md
    - Installation: installation.md
    - Tutorial:
        - '- - segpy module' : segpy_module.md
        - '- - segpy slurm' : segpy_slurm.md
        - '- - segpy local' : segpy_local.md
        - '- - container' : container.md
    - FAQ : FAQ.md        
    - Reference : reference.md        
    - About:
        - '- License': 'LICENSE.md'
        - '- Changelog': 'changelog.md'
        - '- Contributing': contributing.md
        - '- Acknowledgement': Acknowledgement.md
theme: readthedocs
# Customization
extra:
  version:
    default: stable 
