site_name: segpy
site_url: https://neurobioinfo.github.io/
nav:
    - Home: index.md
    - Installation: installation.md
    - Tutorial:
        - '- slurm' : segpy.md
        - '- slurm' : segpy_slurm.md
    - FAQ : FAQ.md        
    - Reference : reference.md        
    - About:
        - '- License': 'LICENSE.md'
        - '- Changelog': 'changelog.md'
        - '- Contributing': contributing.md
        - '- Acknowledgement': Acknowledgement.md
theme: readthedocs

