site_name: segpy
site_url: https://neurobioinfo.github.io/
nav:
    - Home: index.md
    - Tutorial:
        - Installation: installation.md 
        - Segpy SLURM: segpy_slurm.md
        - Segpy Local: segpy_local.md
        - Configuration parameters : reference.md 
        - Output files: output.md 
        - FAQ : FAQ.md           
    - About:
        - 'License': 'LICENSE.md'
        - 'Changelog': 'changelog.md'
        - 'Contributing': contributing.md
        - 'Acknowledgement': Acknowledgement.md
theme: readthedocs
# Customization
# extra:
#   version:
#     default: stable 
