#!/bin/bash

#PBS -l walltime=168:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002
echo timestamp $(date +%s)

echo "*******************************************"
echo "* step3"
echo "*******************************************"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
echo "*******************************************"

#-----------------------------------------------------#
# Clean Output file                                   #
#-----------------------------------------------------#
# 


FINALFILE=$OUTPUT_DIR/finalseg.csv

sed  -e "s/\"//g; s/\[//g; s/\]//g; s/\, /\|/g; s/\,/\|/g"  $OUTPUT_DIR/finalseg.csv  >  $OUTPUT_DIR/finalseg_modified.csv

