#!/bin/bash

#PBS -l walltime=168:0:0
#PBS -r n
#PBS -j oe
#PBS -W umask=002

umask 002
echo timestamp $(date +%s)



echo "*******************************************"
echo "* step2"
echo "*******************************************"
echo "* PIPELINE_HOME:        $PIPELINE_HOME"
echo "* DIR:                  $OUTPUT_DIR"
echo "* VCF:                  $VCF"
echo "* PED:                  $PED"
echo "* NCOL:                 $NCOL"
echo "* SPARKMEM:             $SPARKMEM"
echo "*******************************************"

#-----------------------------------------------------#
# Step2: Run Segrun                                     #
#-----------------------------------------------------#

export SPARK_HOME=$PIPELINE_HOME/soft/spark-3.1.2-bin-hadoop3.2
export SPARK_LOG_DIR=$OUTPUT_DIR/logs/spark
module load java/11.0.2
${SPARK_HOME}/sbin/start-master.sh
source ${BASEFOLDER}/hail_env/bin/activate
export PYTHONPATH=$BASEFOLDER/hail_env/lib/python3.8/site-packages
module  load python/3.8.10  


file2=$(basename $VCF)
MTFILE=$OUTPUT_DIR/${file2%.*}.mt

${BASEFOLDER}/hail_env/bin/python3.8  ${PIPELINE_HOME}/scripts/step2/step2.py $MTFILE $OUTPUT_DIR $PED $VCF $NCOL $SPARKMEM
